import { Inject, Logger } from '@nestjs/common';
import { Processor, WorkerHost } from '@nestjs/bullmq';
import { Job } from 'bullmq';
import { AiGeneratorRepository } from '../../ai-generator/ai-generator.repository';
import { CardService } from '../../card/card.service';
import { CreateDeckDto } from '../../deck/dto/create-deck.dto';
import { DeckService } from '../../deck/deck.service';
import {
  FLASHCARD_GENERATE_JOB,
  FLASHCARD_GENERATE_QUEUE,
} from '../constants/chatbot.constants';
import { ChatbotRepository } from '../chatbot.repository';
import { AI_PROVIDER } from '../interfaces/ai-provider.interface';
import type { IAiProvider } from '../interfaces/ai-provider.interface';
import { FlashcardGenerateJobData } from '../interfaces/flashcard-generate-job-data.interface';

@Processor(FLASHCARD_GENERATE_QUEUE)
export class FlashcardGenerateProcessor extends WorkerHost {
  private readonly logger = new Logger(FlashcardGenerateProcessor.name);

  constructor(
    @Inject(AI_PROVIDER)
    private readonly aiProvider: IAiProvider,
    private readonly aiGeneratorRepository: AiGeneratorRepository,
    private readonly deckService: DeckService,
    private readonly cardService: CardService,
    private readonly chatbotRepository: ChatbotRepository,
  ) {
    super();
  }

  async process(job: Job<FlashcardGenerateJobData>): Promise<void> {
    if (job.name !== FLASHCARD_GENERATE_JOB) {
      return;
    }

    const data = job.data;

    try {
      await this.aiGeneratorRepository.updateJobStatus(data.jobId, 'running');
      await job.updateProgress(10);

      const aiResult = await this.aiProvider.generateFlashcards(
        data.content,
        data.options,
      );
      await job.updateProgress(60);

      const deckPayload = {
        title: data.title,
        description:
          data.deckDescription ??
          'Flashcard deck generated by AI from study material',
        visibility: 'private',
        tags: data.deckTags ?? ['ai-generated'],
        sourceType: 'ai',
        aiSourceId: data.sourceId,
        academicDocumentId: data.academicDocumentId,
        subjectId: data.subjectId,
      } as CreateDeckDto & {
        sourceType: 'ai';
        aiSourceId?: string;
        academicDocumentId?: string;
        subjectId?: string;
      };
      const deck = await this.deckService.createDeck(deckPayload, data.userId);
      await job.updateProgress(70);

      const cards = aiResult.cards.map((card, index) => ({
        deckId: deck._id,
        front: card.front,
        back: card.back,
        hint: card.hint,
        explanation: card.explanation,
        examples: card.examples ?? [],
        position: index,
        aiJobId: data.jobId,
      }));

      await this.cardService.createBulkCards({ cards }, data.userId);
      await job.updateProgress(90);

      await this.aiGeneratorRepository.markJobDone(data.jobId, {
        targetDeckId: deck._id,
        usage: {
          inputTokens: aiResult.inputTokens,
          outputTokens: aiResult.outputTokens,
        },
      });

      if (data.conversationId) {
        await this.chatbotRepository.createMessage({
          conversationId: data.conversationId,
          userId: data.userId,
          role: 'assistant',
          content: `Generated deck "${data.title}" with ${cards.length} flashcards.`,
          metadata: {
            aiJobId: data.jobId,
            sourceId: data.sourceId,
            generatedDeckId: deck._id,
            generatedCardCount: cards.length,
            status: 'done',
          },
        });
      }

      await job.updateProgress(100);
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : 'Unknown generation error';

      this.logger.error(errorMessage);
      await this.aiGeneratorRepository.updateJobStatus(
        data.jobId,
        'failed',
        errorMessage,
      );

      if (data.conversationId) {
        await this.chatbotRepository.createMessage({
          conversationId: data.conversationId,
          userId: data.userId,
          role: 'assistant',
          content: `AI flashcard generation failed for "${data.title}".`,
          metadata: {
            aiJobId: data.jobId,
            sourceId: data.sourceId,
            status: 'failed',
            errorMessage,
          },
        });
      }

      throw error;
    }
  }
}
