import { Inject, Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { AiGeneratorRepository } from '../../ai-generator/ai-generator.repository';
import { CardService } from '../../card/card.service';
import { CreateDeckDto } from '../../deck/dto/create-deck.dto';
import { DeckService } from '../../deck/deck.service';
import { ChatbotRepository } from '../chatbot.repository';
import { AI_PROVIDER } from '../interfaces/ai-provider.interface';
import type { IAiProvider } from '../interfaces/ai-provider.interface';
import { FlashcardGenerateJobData } from '../interfaces/flashcard-generate-job-data.interface';
import { AcademicDocumentStorageService } from './academic-document-storage.service';
import { PdfParserService } from './pdf-parser.service';

type ProgressReporter = (progress: number) => Promise<void> | void;
const DEFAULT_MAX_INPUT_CHARS = 50000;

@Injectable()
export class FlashcardGenerationRunnerService {
  private readonly logger = new Logger(FlashcardGenerationRunnerService.name);

  constructor(
    @Inject(AI_PROVIDER)
    private readonly aiProvider: IAiProvider,
    private readonly aiGeneratorRepository: AiGeneratorRepository,
    private readonly deckService: DeckService,
    private readonly cardService: CardService,
    private readonly chatbotRepository: ChatbotRepository,
    private readonly storageService: AcademicDocumentStorageService,
    private readonly pdfParserService: PdfParserService,
    private readonly configService: ConfigService,
  ) {}

  async run(
    data: FlashcardGenerateJobData,
    reportProgress?: ProgressReporter,
  ): Promise<void> {
    const runningJob = await this.aiGeneratorRepository.markJobRunningIfQueued(
      data.jobId,
    );

    if (!runningJob) {
      const currentJob = await this.aiGeneratorRepository.findJobById(
        data.jobId,
      );
      this.logger.warn(
        `Skipping AI job ${data.jobId}; current status is ${
          currentJob?.status ?? 'missing'
        }`,
      );
      return;
    }

    try {
      await reportProgress?.(10);

      const content = await this.resolveContent(data);
      await reportProgress?.(25);

      const aiResult = await this.aiProvider.generateFlashcards(
        content,
        data.options,
      );
      await reportProgress?.(60);

      const deckPayload = {
        title: data.title,
        description:
          data.deckDescription ??
          'Flashcard deck generated by AI from study material',
        visibility: 'private',
        tags: data.deckTags ?? ['ai-generated'],
        sourceType: 'ai',
        aiSourceId: data.sourceId,
        academicDocumentId: data.academicDocumentId,
        subjectId: data.subjectId,
      } as CreateDeckDto & {
        sourceType: 'ai';
        aiSourceId?: string;
        academicDocumentId?: string;
        subjectId?: string;
      };

      const deck = await this.deckService.createDeck(deckPayload, data.userId);
      await reportProgress?.(70);

      const cards = aiResult.cards.map((card, index) => ({
        deckId: deck._id,
        front: card.front,
        back: card.back,
        hint: card.hint,
        explanation: card.explanation,
        examples: card.examples ?? [],
        position: index,
        aiJobId: data.jobId,
      }));

      await this.cardService.createBulkCards({ cards }, data.userId);
      await reportProgress?.(90);

      await this.aiGeneratorRepository.markJobDone(data.jobId, {
        targetDeckId: deck._id,
        usage: {
          inputTokens: aiResult.inputTokens,
          outputTokens: aiResult.outputTokens,
        },
      });

      if (data.conversationId) {
        await this.chatbotRepository.createMessage({
          conversationId: data.conversationId,
          userId: data.userId,
          role: 'assistant',
          content: `Generated deck "${data.title}" with ${cards.length} flashcards.`,
          metadata: {
            aiJobId: data.jobId,
            sourceId: data.sourceId,
            generatedDeckId: deck._id,
            generatedCardCount: cards.length,
            status: 'done',
          },
        });
      }

      await reportProgress?.(100);
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : 'Unknown generation error';

      this.logger.error(errorMessage);
      await this.aiGeneratorRepository.updateJobStatus(
        data.jobId,
        'failed',
        errorMessage,
      );

      if (data.conversationId) {
        await this.chatbotRepository.createMessage({
          conversationId: data.conversationId,
          userId: data.userId,
          role: 'assistant',
          content: `AI flashcard generation failed for "${data.title}".`,
          metadata: {
            aiJobId: data.jobId,
            sourceId: data.sourceId,
            status: 'failed',
            errorMessage,
          },
        });
      }

      throw error;
    }
  }

  private async resolveContent(data: FlashcardGenerateJobData) {
    if (data.content?.trim()) {
      return this.truncateInput(data.content);
    }

    if (data.storagePath) {
      const fileBuffer = await this.storageService.download(
        data.storagePath,
        data.fileUrl,
      );

      return this.truncateInput(
        await this.pdfParserService.extractText(fileBuffer),
      );
    }

    throw new Error('No input content available for AI generation');
  }

  private truncateInput(content: string) {
    const maxChars = this.getPositiveIntConfig(
      'CHATBOT_MAX_INPUT_CHARS',
      DEFAULT_MAX_INPUT_CHARS,
    );

    return content.slice(0, maxChars);
  }

  private getPositiveIntConfig(key: string, fallback: number) {
    const rawValue = this.configService.get<string | number>(key);
    const parsedValue =
      typeof rawValue === 'number'
        ? rawValue
        : Number.parseInt(String(rawValue ?? ''), 10);

    return Number.isFinite(parsedValue) && parsedValue > 0
      ? parsedValue
      : fallback;
  }
}
